### ISSUE TITLE
Feature1

### ISSUE THREAD

**Issue by cabalito** [jmolinma/IWVG.SwC.JavierMolina#1]
Buenas noches,

Es necesario añadir el método "InitialWithFamilyName" a la clase "User".  [Más información ](https://github.com/jmolinma/IWVG.SwC.JavierMolina/wiki#se-plantean-las-siguientes-mejoras-para-la-clase-user)

**Comment by cabalito** [comment]
Buenas tardes, en el milestone está fijado un deadline, su necesitas más tiempo házmelo saber.
Por favor confirma que lo has recibido.

**Comment by EneasVVA** [comment]
Roger that
