### ISSUE TITLE
Feature2

### ISSUE THREAD

**Issue by cabalito** [jmolinma/IWVG.SwC.JavierMolina#2]
Buenas noches,

Es necesario añadir el método "Sum" a la clase "Point". [Más información](https://github.com/jmolinma/IWVG.SwC.JavierMolina/wiki#se-plantean-las-siguientes-mejoras-para-la-clase-point)

**Comment by cabalito** [comment]
Buenas tardes, en el milestone está fijado un deadline, su necesitas más tiempo házmelo saber.
Por favor confirma que lo has recibido.

**Comment by kikevillab** [comment]
Recibido! mañana lo hago

**Comment by kikevillab** [comment]
Hecho!.

**Comment by cabalito** [comment]
Todo correcto, gracias
