### ISSUE TITLE
Feature 3

### ISSUE THREAD

**Issue by cabalito** [jmolinma/IWVG.SwC.JavierMolina#4]
Buenas noches,

Es necesario añadir el método "Remove" a la clase "DecimalCollection". [Más información](https://github.com/jmolinma/IWVG.SwC.JavierMolina/wiki#se-plantean-las-siguientes-mejoras-para-la-clase-decimalcollection)

**Comment by cabalito** [comment]
Buenas tardes, en el milestone está fijado un deadline, su necesitas más tiempo házmelo saber.
Por favor confirma que lo has recibido.

**Comment by caguilar1990** [comment]
Javier, he hecho un commit! no sé si lo he hecho bien, avisame cualquier cosa

**Comment by caguilar1990** [comment]
Creo ya lo he hecho bien, y he hecho un merge con develop

**Comment by cabalito** [comment]
Buenas,
Los cambios no están actualizados en develop, por lo que intuyo que no has realizado un merge. Te cuento los pasos que deberías seguir aunque probablemente alguno ya lo habrás realizado:
1. clonas las ramas feature que te afecten y la develop.
2.realizas las mejoras en cada una de las ramas.
3. una vez realizados y guardados los cambios, seleccionas la carpeta del proyecto en la sección "Project Explorer" de Eclipse (en la parte superior izquierda).
4. sobre cada rama haces click con el botón derecho del ratón, seleccionas la opción "Fetch from Upstream" y posteriormente  "Push branch" para subir la rama al servidor.
5. haces doble click sobre la rama develop y una vez que tiene el check seleccionas la rama para realizar un merge con el botón derecho sobre la rama que vas a juntar con develop. (No olvides seleccionar la opcion "Force commit" en el menú que te aparece al realizar el merge).
6. repite el paso anterior con la otra rama en la que has realizado los cambios.

Espero haberte ayudado.

**Comment by caguilar1990** [comment]
No me digasss!!! he hecho esoo!!!
voy a intentarlo otra vez

**Comment by caguilar1990** [comment]
Graciiassssssss

**Comment by cabalito** [comment]
Ahora los cambios se han subido correctamente.
Mañana está fijado la creación de la release; por lo que pasaré los test. Si tengo algún problema te lo haré saber.
Muchas gracias por tu trabajo y atender las respuestas.
Un saludo

**Comment by caguilar1990** [comment]
Una preguntilla Javier, como cierras los deadine??

**Comment by cabalito** [comment]
Cuando seleccionas "Close and comment" en lugar de sólo "Comment" el "Issue" se cierra y por tanto el "milestone" (o "deadline") que le has asociado también.
¿He respondido a tu pregunta?
